import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import './sass/style.scss'
import CustomCursor from "./components/CustomCursor/CustomCursor";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";
import 'aos/dist/aos.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Davis - Personal portfolio Nextjs template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <CustomCursor />
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
